### ISSUE TITLE
Error: Module com.pylonproducts.wifiwizard.WifiWizard does not exist.

### ISSUE THREAD

**Issue by saoron** [dride/dride-app#25]
https://sentry.io/dride-inc/dride-app/issues/342038702/

```
Error: Module com.pylonproducts.wifiwizard.WifiWizard does not exist.
  at addEntry (/cordova.js:1389:24)
  at clobbers (/cordova.js:1399:13)
  at onScriptLoadingComplete (/cordova.js:1623:38)
  at scriptLoadedCallback (/cordova.js:1656:36)
  at o (/polyfills.js:2:24349)
...
(3 additional frame(s) were not displayed)
```

**Comment by saoron** [comment]
Duplicate #35
