### ISSUE TITLE
Error: Uncaught (in promise): Response with status: 526 Ok for URL: null

### ISSUE THREAD

**Issue by saoron** [dride/dride-app#32]
https://sentry.io/dride-inc/dride-app/issues/344179990/

```
Error: Uncaught (in promise): Response with status: 526 Ok for URL: null
  at c (/polyfills.js:3:13535)
  at None (/polyfills.js:3:14107)
  at t.invokeTask (/polyfills.js:3:9967)
  at Object.inner.inner.fork.onInvokeTask (/vendor.js:1:79031)
  at t.invokeTask (/polyfills.js:3:9888)
...
(4 additional frame(s) were not displayed)
```

**Comment by saoron** [comment]
Duplicate #38
