### ISSUE TITLE
Response with status: 0  for URL: null

### ISSUE THREAD

**Issue by saoron** [dride/dride-app#37]
Lock menu button while we wait for connection....

https://sentry.io/dride-inc/dride-app/issues/346301183/

```
Stacktrace (most recent call first):

  at o.captureException (/vendor.js:1:1634769)
  at XMLHttpRequest.r (/vendor.js:1:1634240)
  at t.invokeTask (/polyfills.js:3:9967)
  at Object.onInvokeTask (/vendor.js:1:79031)
  at t.invokeTask (/polyfills.js:3:9888)
  at r.runTask (/polyfills.js:3:5143)
  at XMLHttpRequest.invoke (/polyfills.js:3:10945)

Response with status: 0  for URL: null
```

**Comment by saoron** [comment]
duplicate #38
